Repository LIKELION-Android-Bootcamp-4th/AOS-05-DamDiet, pull requests merged in 2025-07, with the labels that each got.

#81 Feat/network
  lib/main.dart
  lib/models/Product.dart
  lib/provider/product_provider.dart
  lib/screen/home_screen.dart
  lib/service/api_client.dart
  lib/service/product_api/product_api.dart
  pubspec.lock
  pubspec.yaml
Labels: Feature

#84 Feat/home UI 완성 및 임시 API 데이터 바인딩
  android/gradle.properties
  devtools_options.yaml
  lib/main.dart
  lib/screen/home/home_screen.dart
  lib/screen/home/widgets/category_list.dart
  lib/screen/home/widgets/category_list_item.dart
  lib/screen/home/widgets/home_banner.dart
  lib/screen/home/widgets/list_title.dart
  lib/screen/home/widgets/notice_banner.dart
  lib/screen/home/widgets/product_list.dart
  lib/screen/home/widgets/product_list_item.dart
  lib/screen/home_screen.dart
  lib/widgets/bottom_nav_bar.dart
  lib/widgets/underline_text.dart
  pubspec.lock
  pubspec.yaml
Labels: Design

#87 Feat/cart 장바구니 UI
  android/gradle.properties
  devtools_options.yaml
  lib/main.dart
  lib/screen/cart_screen.dart
  lib/screen/home/home_screen.dart
  lib/screen/home/widgets/category_list.dart
  lib/screen/home/widgets/category_list_item.dart
  lib/screen/home/widgets/home_banner.dart
  lib/screen/home/widgets/list_title.dart
  lib/screen/home/widgets/notice_banner.dart
  lib/screen/home/widgets/product_list.dart
  lib/screen/home/widgets/product_list_item.dart
  lib/screen/home_screen.dart
  lib/widgets/bottom_nav_bar.dart
  lib/widgets/underline_text.dart
  pubspec.lock
  pubspec.yaml
Labels: Design

#93 Feat/product detail 상품상세화면 UI 구현 완
  assets/icons/ic_cancel.svg
  lib/main.dart
  lib/models/Review.dart
  lib/screen/search/product_detail/product_detail_screen.dart
  lib/screen/search/product_detail/widgets/product_detail_info.dart
  lib/screen/search/product_detail/widgets/product_detail_main_info.dart
  lib/screen/search/product_detail/widgets/product_image.dart
  lib/screen/search/product_detail/widgets/product_quantity_selector.dart
  lib/screen/search/product_detail/widgets/product_review_list_item.dart
  lib/screen/search/product_detail/widgets/product_reviews.dart
  lib/screen/search/product_detail_screen.dart
  lib/widgets/underline_text.dart
  pubspec.lock
  pubspec.yaml
Labels: Design

#96 Feat/favorite products 관심 상품 화면 UI 완성
  lib/main.dart
  lib/models/FavoriteProduct.dart
  lib/models/Product.dart
  lib/screen/mypage/mypage_favorite_products_screen.dart
  lib/screen/mypage/mypage_favorite_products_screen/mypage_favorite_products_screen.dart
  lib/screen/mypage/mypage_favorite_products_screen/widgets/favorite_list_item.dart
Labels: Design

#97 feat(#70): 나의 리뷰 목록 화면 UI 구성 완성
  lib/main.dart
  lib/models/MyReview.dart
  lib/models/Product.dart
  lib/screen/mypage/mypage_my_review_screen.dart
  lib/screen/mypage/mypage_my_reviews/mypage_my_reviews_screen.dart
  lib/screen/mypage/mypage_my_reviews/widgets/mypage_review_list_item.dart
  lib/widgets/confirm_dialog.dart
Labels: UI

#99 Feat/login 로그인 임시 고정값 통신 + 토큰 저장
  lib/constants/constants.dart
  lib/core/secure/user_secure_storage.dart
  lib/main.dart
  lib/provider/signin_provider.dart
  lib/screen/login/login_signin_screen.dart
  lib/service/api_client.dart
  lib/service/product_api/login_service.dart
  lib/util/app_value.dart
  pubspec.lock
  pubspec.yaml
Labels: Feature

#101 Feat/login Dio 객체 수정
  lib/core/constants/constants.dart
  lib/core/network/api_client.dart
  lib/service/api_client.dart
  lib/service/product_api/login_service.dart
  lib/service/product_api/product_api.dart
Labels: Feature

#103 My reviews 리뷰등록,리뷰작성 화면 UI 완성
  android/gradle.properties
  lib/main.dart
  lib/screen/mypage/mypage_my_order_details/mypage_my_order_details_screen.dart
  lib/screen/review/review_edit_screen.dart
  lib/screen/review/review_write_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: UI

#104 Feat/login login 로직 변경 중 파일 구조 변경을 위한 PR
  lib/core/constants/constants.dart
  lib/main.dart
  lib/routes/app_routes.dart
  lib/screen/auth/email_verification_screen.dart
  lib/screen/auth/login_signin_screen.dart
  lib/screen/auth/login_signup_screen.dart
  lib/screen/auth/set_nickname_screen.dart
  lib/screen/auth/signin_viewmodel.dart
  lib/screen/auth/widgets/custom_textfield.dart
  lib/screen/auth/widgets/sign_up_prompt.dart
  lib/screen/auth/widgets/status_message_text.dart
  lib/screen/community/kcal_calculator_screen.dart
  lib/screen/mypage/mypage_password_edit_screen.dart
  lib/screen/mypage/mypage_profile_edit_screen.dart
  lib/screen/splash/splash_screen.dart
  lib/screen/splash/splash_viewmodel.dart
  lib/service/product_api/login_service.dart
Labels: Feature

#109 Feat/home 상품 리스트 3개 모두 구현, 홈 배너 완성
  lib/core/network/endpoint/product_endpoints.dart
  lib/core/utils/formatters.dart
  lib/data/datasource/product_datasource.dart
  lib/data/models/product/product.dart
  lib/data/models/product/product_nutrition.dart
  lib/data/models/response/product_list_response.dart
  lib/data/repositories/product_repository.dart
  lib/presentation/screens/home/home_screen.dart
  lib/presentation/screens/home/home_viewmodel.dart
  lib/presentation/screens/home/widgets/category_list.dart
  lib/presentation/screens/home/widgets/category_list_item.dart
  lib/presentation/screens/home/widgets/home_banner.dart
  lib/presentation/screens/home/widgets/product_list_item.dart
  pubspec.lock
  pubspec.yaml
Labels: Feature

#111 feat(#39): ViewModel에 상품 수량 증감 로직 추가
  lib/core/utils/formatters.dart
  lib/presentation/screens/cart/widgets/cart_quantity_control.dart
  lib/presentation/screens/product_detail/product_detail_screen.dart
  lib/presentation/screens/product_detail/product_detail_viewmodel.dart
  lib/presentation/screens/product_detail/widgets/product_quantity_selector.dart
Labels: Feature

#115 Feat/login login 기능 구현
  lib/core/constants/constants.dart
  lib/core/network/SessionExpiredException.dart
  lib/core/network/api_client.dart
  lib/data/datasource/login_service.dart
  lib/data/models/auth/user.dart
  lib/data/models/response/api_response.dart
  lib/data/models/response/login_response.dart
  lib/data/repositories/login_repository.dart
  lib/presentation/screens/auth/auth_signin_screen.dart
  lib/presentation/screens/auth/signin_viewmodel.dart
Labels: Feature

#116 Feat/login 회원가입 기능 구현
  lib/core/network/endpoint/auth_endpoints.dart
  lib/core/utils/validation.dart
  lib/data/datasource/login_service.dart
  lib/data/repositories/login_repository.dart
  lib/main.dart
  lib/presentation/screens/auth/auth_signup_screen.dart
  lib/presentation/screens/auth/signup_viewmodel.dart
Labels: Feature

#118 feat: 칼로리 계산기 API 연결
  lib/core/constants/constants.dart
  lib/core/network/nut_api_client.dart
  lib/data/datasource/nutrition_dataresource.dart
  lib/data/models/kcal/nut_api_item.dart
  lib/data/models/response/nut_api_response.dart
  lib/data/repositories/nutrition_repository.dart
  lib/main.dart
  lib/presentation/screens/kcal_calculator/kcal_calculator_screen.dart
  lib/presentation/screens/kcal_calculator/kcal_calculator_viewmodel.dart
  lib/presentation/screens/kcal_calculator/widgets/kcal_listview_item.dart
Labels: Feature

#117 Feat/product detail 찜 기능 추가
  lib/core/network/endpoint/favorite_products_endpoints.dart
  lib/core/network/endpoint/product_endpoints.dart
  lib/data/datasource/product_datasource.dart
  lib/data/models/product/product.dart
  lib/data/repositories/product_repository.dart
  lib/presentation/screens/product_detail/product_detail_screen.dart
  lib/presentation/screens/product_detail/product_detail_viewmodel.dart
  lib/presentation/screens/product_detail/widgets/product_review_list_item.dart
  lib/presentation/screens/product_detail/widgets/product_reviews.dart
Labels: Feature

#123 feat(#42): product_detail 화면에서 장바구니 담기 로직 구현
  lib/core/exceptions/quantity_invalid_exception.dart
  lib/core/exceptions/session_expired_exception.dart
  lib/core/network/api_client.dart
  lib/data/datasource/product_datasource.dart
  lib/data/models/cart/cart_request.dart
  lib/data/repositories/product_repository.dart
  lib/presentation/screens/product_detail/product_detail_screen.dart
  lib/presentation/screens/product_detail/product_detail_viewmodel.dart
Labels: Feature

#124 feat(#54): 로그아웃(토큰 제거) 후 로그인 화면으로 이동까지 구현
  lib/main.dart
  lib/presentation/screens/mypage/mypage/mypage_screen.dart
  lib/presentation/screens/mypage/mypage/mypage_viewmodel.dart
  lib/presentation/screens/mypage/mypage/widgets/mypage_contents.dart
Labels: Feature

#127 Feat/cart UI, Repository 리팩토링
  lib/data/datasource/cart_datasource.dart
  lib/data/repositories/cart_repository.dart
  lib/main.dart
  lib/presentation/screens/cart/cart_view_model.dart
  lib/presentation/screens/cart/widgets/cart_item_card.dart
Labels: Refactoring

#128 Feat/search, payment 화면의 viewmodel, provider 문제 해결
  lib/core/widgets/category_outline_button.dart
  lib/core/widgets/outline_chip_group.dart
  lib/core/widgets/search_product_textfield.dart
  lib/presentation/provider/price_range_provider.dart
  lib/presentation/screens/payment/payment_screen.dart
  lib/presentation/screens/payment/widgets/select_payment._widget.dart
  lib/presentation/screens/products/products_screen.dart
  lib/presentation/screens/search/search_screen.dart
  lib/presentation/screens/search/search_viewmodel.dart
Labels: Bug

#129 feat(#43): product_detail -> payment 에 List<OrderItem> argu 추가
  lib/data/models/request/order_request_dto.dart
  lib/main.dart
  lib/presentation/screens/mypage/mypage_my_orders/widgets/mypage_order_card_item.dart
  lib/presentation/screens/mypage/mypage_my_orders_screen.dart
  lib/presentation/screens/payment/payment_screen.dart
  lib/presentation/screens/product_detail/product_detail_screen.dart
Labels: Feature

#130 feat: 칼로리 계산기 기능 완성
  android/gradle.properties
  lib/data/datasource/nutrition_dataresource.dart
  lib/data/models/kcal/product_nutrition.dart
  lib/data/models/response/nut_api_response.dart
  lib/data/repositories/nutrition_repository.dart
  lib/models/ProductNutrition.dart
  lib/presentation/screens/kcal_calculator/kcal_calculator_screen.dart
  lib/presentation/screens/kcal_calculator/kcal_calculator_viewmodel.dart
  lib/presentation/screens/kcal_calculator/widgets/kcal_checked_item.dart
  lib/presentation/screens/kcal_calculator/widgets/kcal_checked_list.dart
  lib/presentation/screens/kcal_calculator/widgets/kcal_listview_item.dart
  lib/presentation/screens/kcal_calculator/widgets/kcal_nutrition_dialog.dart
Labels: Feature

#132 Feat/favorite products 목록불러오기/찜삭제/추가/상품상세보기 구현완료
  lib/data/datasource/favorite_datasource.dart
  lib/data/models/favorite_product/favorite_product.dart
  lib/data/models/product/favorite_summary_product.dart
  lib/data/models/response/favorite_response.dart
  lib/data/repositories/favorite_repository.dart
  lib/main.dart
  lib/presentation/screens/mypage/mypage_favorite_product/mypage_favorite_products_screen.dart
  lib/presentation/screens/mypage/mypage_favorite_product/mypage_favorite_products_viewmodel.dart
  lib/presentation/screens/mypage/mypage_favorite_product/widgets/favorite_list_item.dart
Labels: Feature

#135 Feat/my profile edit 배송지 변경
  lib/data/datasource/mypage_datasource.dart
  lib/data/datasource/nutrition_datasource.dart
  lib/data/repositories/mypage_repository.dart
  lib/data/repositories/nutrition_repository.dart
  lib/main.dart
  lib/presentation/screens/mypage/mypage/mypage_screen.dart
  lib/presentation/screens/mypage/mypage/mypage_viewmodel.dart
  lib/presentation/screens/mypage/mypage_address_edit_screen.dart
Labels: Feature

#138 Feat/viewmodel di main.dart 충돌 해결
  lib/main.dart
Labels: Bug

#139 feat(#48): 카테고리별 상품보기 구현
  lib/presentation/screens/cart/cart_view_model.dart
  lib/presentation/screens/home/home_screen.dart
Labels: Feature

#140 Feat/my profile edit 배송지 변경화면에 기존 배송지 불러오기
  lib/data/datasource/mypage_datasource.dart
  lib/data/repositories/mypage_repository.dart
  lib/presentation/screens/mypage/mypage/mypage_viewmodel.dart
  lib/presentation/screens/mypage/mypage_address_edit_screen.dart
Labels: Feature

#142 Feat/my profile edit
  lib/core/widgets/bottom_cta_button.dart
  lib/data/datasource/mypage_datasource.dart
  lib/data/models/auth/profile_update_payload.dart
  lib/data/repositories/mypage_repository.dart
  lib/main.dart
  lib/presentation/routes/app_routes.dart
  lib/presentation/screens/auth/widgets/custom_textfield.dart
  lib/presentation/screens/mypage/mypage/widgets/mypage_contents.dart
  lib/presentation/screens/mypage/mypage_nickname_edit/mypage_nickname_edit_screen.dart
  lib/presentation/screens/mypage/mypage_nickname_edit/mypage_nickname_edit_viewmodel.dart
  lib/presentation/screens/mypage/mypage_password_edit/mypage_password_edit_screen.dart
  lib/presentation/screens/mypage/mypage_password_edit/mypage_password_edit_viewmodel.dart
  lib/presentation/screens/mypage/mypage_password_edit_screen.dart
Labels: Feature

#143 Feat/whole refine 전체적 리팩토링 및 카트, 찜 기능 안되던거 수정
  lib/data/models/cart/cart_product.dart
  lib/data/models/favorite_product/favorite_product.dart
  lib/data/models/product/favorite_summary_product.dart
  lib/presentation/screens/mypage/mypage_favorite_product/mypage_favorite_products_screen.dart
  lib/presentation/screens/mypage/mypage_favorite_product/mypage_favorite_products_viewmodel.dart
  lib/presentation/screens/mypage/mypage_favorite_product/widgets/favorite_list_item.dart
Labels: Refactoring

#146 Feat/my orders
  lib/core/network/endpoint/mypage_endpoints.dart
  lib/core/utils/extract_date.dart
  lib/data/datasource/order_datasource.dart
  lib/data/models/order/my_order_detail.dart
  lib/data/models/order/my_order_item.dart
  lib/data/models/response/my_orders_response.dart
  lib/data/repositories/order_repository.dart
  lib/main.dart
  lib/presentation/screens/mypage/mypage_my_order_detail/mypage_my_order_details_screen.dart
  lib/presentation/screens/mypage/mypage_my_order_detail/order_detail_viewmodel.dart
  lib/presentation/screens/mypage/mypage_my_order_detail/widgets/mypage_order_product_item_row.dart
  lib/presentation/screens/mypage/mypage_my_order_detail/widgets/mypage_order_product_list_section.dart
  lib/presentation/screens/mypage/mypage_my_orders/mypage_my_orders_screen.dart
  lib/presentation/screens/mypage/mypage_my_orders/order_viewmodel.dart
  lib/presentation/screens/mypage/mypage_my_orders/widgets/mypage_order_card.dart
  lib/presentation/screens/mypage/mypage_my_orders/widgets/mypage_order_card_bottom.dart
  lib/presentation/screens/mypage/mypage_my_orders/widgets/mypage_order_card_header.dart
  lib/presentation/screens/mypage/mypage_my_orders/widgets/mypage_order_card_item.dart
  lib/presentation/screens/mypage/mypage_my_orders_screen.dart
Labels: Feature

#162 fix: 주문 상세에서 이미 작성한 리뷰의 상품은 리뷰작성 버튼이 보이지 않도록 수정
  lib/data/models/order/my_order_item.dart
  lib/presentation/screens/mypage/mypage_my_order_detail/widgets/mypage_order_product_item_row.dart
Labels: Refactoring

#168 Feat/payment 결제 기능 완성
  android/gradle.properties
  lib/data/datasource/payment_service.dart
  lib/data/repositories/payment_repository.dart
  lib/main.dart
  lib/presentation/screens/cart/widgets/cart_order_summary.dart
  lib/presentation/screens/payment/payment_screen.dart
  lib/presentation/screens/payment/payment_viewmodel.dart
  lib/presentation/screens/payment/widgets/payment_checkbox_widget.dart
  lib/presentation/screens/payment/widgets/select_payment._widget.dart
  lib/presentation/screens/product_detail/product_detail_screen.dart
Labels: Feature

#167 Feat/whole refine 유저 정보 전역으로 들고있게끔 수정, 장바구니 수량 버튼 크기 조정
  lib/core/widgets/damdiet_appbar.dart
  lib/data/models/auth/user.dart
  lib/main.dart
  lib/presentation/provider/user_provider.dart
  lib/presentation/screens/cart/widgets/cart_quantity_control.dart
  lib/presentation/screens/mypage/mypage/widgets/mypage_header.dart
  lib/presentation/screens/mypage/mypage_nickname_edit/mypage_nickname_edit_screen.dart
  lib/presentation/screens/mypage/mypage_nickname_edit/mypage_nickname_edit_viewmodel.dart
  lib/presentation/screens/splash/splash_screen.dart
  lib/presentation/screens/splash/splash_viewmodel.dart
Labels: Feature

#172 Feat/whole refine
  lib/core/widgets/category_outline_button.dart
  lib/core/widgets/product_list_item.dart
  lib/core/widgets/search_product_textfield.dart
  lib/presentation/provider/nutrition_provider.dart
  lib/presentation/provider/price_range_provider.dart
  lib/presentation/provider/search_provider.dart
  lib/presentation/screens/cart/widgets/cart_item_card.dart
  lib/presentation/screens/cart/widgets/cart_order_summary.dart
  lib/presentation/screens/cart/widgets/cart_price_info.dart
  lib/presentation/screens/kcal_calculator/kcal_calculator_screen.dart
  lib/presentation/screens/kcal_calculator/widgets/kcal_checked_item.dart
  lib/presentation/screens/kcal_calculator/widgets/kcal_checked_list.dart
  lib/presentation/screens/kcal_calculator/widgets/kcal_listview_item.dart
  lib/presentation/screens/mypage/mypage_favorite_product/mypage_favorite_products_screen.dart
  lib/presentation/screens/mypage/mypage_favorite_product/widgets/favorite_empty_view.dart
  lib/presentation/screens/payment/payment_screen.dart
  lib/presentation/screens/payment/widgets/payment_checkbox_widget.dart
  lib/presentation/screens/payment/widgets/payment_list_item.dart
Labels: Refactoring

#175 Feat/whole refine #173, #171 수정
  assets/images/app_name.png
  lib/core/widgets/damdiet_appbar.dart
  lib/presentation/screens/auth/auth_signin_screen.dart
  lib/presentation/screens/mypage/mypage_favorite_product/widgets/favorite_list_item.dart
  lib/presentation/screens/product_detail/product_detail_screen.dart
  lib/presentation/screens/product_detail/widgets/product_reviews.dart
Labels: Bug

#180 Feat/whole refine 전체적인 버그 수정
  assets/images/empty_image.png
  lib/core/widgets/product_list_item.dart
  lib/data/datasource/cart_datasource.dart
  lib/data/models/cart/cart_item.dart
  lib/data/models/cart/cart_product.dart
  lib/data/models/cart/cart_request.dart
  lib/data/models/cart/discount.dart
  lib/data/repositories/cart_repository.dart
  lib/data/repositories/product_repository.dart
  lib/presentation/screens/cart/widgets/cart_empty_view.dart
  lib/presentation/screens/cart/widgets/cart_order_summary.dart
  lib/presentation/screens/mypage/mypage_favorite_product/widgets/favorite_empty_view.dart
  lib/presentation/screens/mypage/mypage_favorite_product/widgets/favorite_list_item.dart
  lib/presentation/screens/mypage/mypage_my_reviews/mypage_my_reviews_screen.dart
  lib/presentation/screens/payment/widgets/payment_list_item.dart
  lib/presentation/screens/product_detail/product_detail_viewmodel.dart
Labels: Bug, Refactoring

#183 fix: 영양상세 다이얼로그 닫으면 키보드 올라오는 버그 수정
  lib/presentation/screens/kcal_calculator/widgets/kcal_nutrition_dialog.dart
Labels: Bug

#184 커뮤니티 관련 스크린 삭제
  lib/main.dart
  lib/presentation/routes/app_routes.dart
  lib/presentation/screens/community/community_detail_screen.dart
  lib/presentation/screens/community/community_home_screen.dart
  lib/presentation/screens/community/community_write_screen.dart
  lib/presentation/screens/home/home_screen.dart
  lib/presentation/screens/payment/payment_screen.dart
Labels: Refactoring
